### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by func0der** [globtec/phpadr#3]
Hey there,

you have made some code changes, for example bumped the symfony/console version.

Will there be a new tag and release or should this repo and the package be considered abandoned?
There is no shame in that, open source is hard work. But, please, let us know :)

func0der

**Comment by globtec** [comment]
Thanks for the question.

I will work on bump the dependencies version soon ;)

**Comment by think-ai** [comment]
Hello there,

I am also facing the same issue, composer require fails with error
```
globtec/phpadr[v2.0.0, ..., v2.0.1] require symfony/console ^4.0 -> found symfony/console[v4.0.0, ..., v4.4.25] but the package is fixed to v5.3.0 (lock file version) by a parti
al update and that version does not match. Make sure you list it as an argument for the update command.
```
Thanks.

**Comment by globtec** [comment]
Sorry for taking so long to fix this issue.

Please,  try to perform `composer require globtec/phpadr` again and share here if it worked.

**Comment by globtec** [comment]
Hello there,

I'm closing this issue, as I said before, when executing the command `composer require globtec/phpadr` no problem should occur.

For more details, see our [releases](https://github.com/globtec/phpadr/releases).

If the problem persists, open a new issue, please. 

Thanks.
