### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by frankvanhest** [globtec/phpadr#7]
Hi @globtec,

Do you have an idea when the current master branch will be tagged for a new release? 

Cheers, Frank

**Comment by func0der** [comment]
Hello. Same question here :)

**Comment by func0der** [comment]
Okay. Project dead, I guess :) 

Thanks for your work up until now :) Have a good one.

**Comment by func0der** [comment]
I am confused. What does "not planned" mean? You are not going to release the current `master` as a new release or you are not working on this library anymore? If it is the later one, please mark the repository as "archived" and the library on packagist.org as "abandoned"
